remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
title: [Carlos Aguirre's ePortfolio ]
description: [SNHU CS-499 Computer Science Capstone]
